rm -f clp.rpt
rm -rf fv/
rm -f *.do
rm -f *.v
rm -f rc.cmd*
rm -f rc.log*
rm -f genus.cmd*
rm -f genus.log*
rm -f *.log*
rm -rf libscore_work
rm -rf LEC.tmp.*
rm -f *.sdc
rm -f *.upf
rm -f phy.innovus.*
rm -f .ilm_fe_view_data
rm -rf rtl_finalv_db/
rm -fr genus2invs_*
rm -rf .oa_import_*
rm -f .*.tstamp